name: Job Concurrency Demo

on:
  push:
    branches:
      - main

concurrency:
  group: example-group
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Print message
        run: echo "Running job with concurrency control 5"
